# Generated by Django 5.2.5 on 2025-09-24 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_guide'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guide',
            name='experience_years',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='guide',
            name='languages',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='guide',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='guides/profiles/'),
        ),
    ]
