# Generated by Django 4.2.2 on 2026-01-15 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_expensecategory_travelbudget_traveldocument_and_more'),
    ]

    operations = [
    ]
