# Generated by Django 5.2.5 on 2026-01-15 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20260115_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelexpense',
            name='booking_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='travelexpense',
            name='is_booking_expense',
            field=models.BooleanField(default=False),
        ),
    ]
