# Generated by Django 5.2.5 on 2026-01-15 19:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_travelexpense_booking_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyProtocol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('altitude_range_min', models.IntegerField()),
                ('altitude_range_max', models.IntegerField()),
                ('location_name', models.CharField(max_length=200)),
                ('rescue_contact', models.CharField(max_length=50)),
                ('helicopter_service', models.CharField(blank=True, max_length=50)),
                ('nearest_hospital', models.CharField(max_length=200)),
                ('descent_route', models.TextField()),
                ('safe_altitude', models.IntegerField(help_text='Safe altitude to descend to')),
                ('estimated_descent_time', models.CharField(max_length=100)),
                ('oxygen_availability', models.BooleanField(default=False)),
                ('medical_post_location', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AcclimatizationPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trek_name', models.CharField(max_length=200)),
                ('start_altitude', models.IntegerField(help_text='Starting altitude in meters')),
                ('target_altitude', models.IntegerField(help_text='Target altitude in meters')),
                ('trek_duration', models.IntegerField(help_text='Trek duration in days')),
                ('risk_level', models.CharField(choices=[('low', 'Low Risk'), ('medium', 'Medium Risk'), ('high', 'High Risk')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AltitudeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('fitness_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='intermediate', max_length=20)),
                ('previous_altitude_experience', models.BooleanField(default=False)),
                ('max_altitude_reached', models.IntegerField(default=0, help_text='Maximum altitude reached in meters')),
                ('has_altitude_sickness_history', models.BooleanField(default=False)),
                ('medical_conditions', models.TextField(blank=True, help_text='Heart, lung, or other relevant conditions')),
                ('medications', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SymptomLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('current_altitude', models.IntegerField()),
                ('headache', models.IntegerField(choices=[(0, 'None'), (1, 'Mild'), (2, 'Moderate'), (3, 'Severe')], default=0)),
                ('nausea', models.IntegerField(choices=[(0, 'None'), (1, 'Mild'), (2, 'Moderate'), (3, 'Severe')], default=0)),
                ('fatigue', models.IntegerField(choices=[(0, 'None'), (1, 'Mild'), (2, 'Moderate'), (3, 'Severe')], default=0)),
                ('dizziness', models.IntegerField(choices=[(0, 'None'), (1, 'Mild'), (2, 'Moderate'), (3, 'Severe')], default=0)),
                ('sleep_difficulty', models.IntegerField(choices=[(0, 'None'), (1, 'Mild'), (2, 'Moderate'), (3, 'Severe')], default=0)),
                ('appetite_loss', models.IntegerField(choices=[(0, 'None'), (1, 'Mild'), (2, 'Moderate'), (3, 'Severe')], default=0)),
                ('confusion', models.BooleanField(default=False)),
                ('difficulty_walking', models.BooleanField(default=False)),
                ('shortness_of_breath_at_rest', models.BooleanField(default=False)),
                ('chest_tightness', models.BooleanField(default=False)),
                ('coughing_blood', models.BooleanField(default=False)),
                ('oxygen_saturation', models.IntegerField(blank=True, help_text='SpO2 percentage', null=True)),
                ('heart_rate', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acclimatization_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.acclimatizationplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
