# Generated by Django 5.2.5 on 2026-02-19 16:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_emergencyprotocol_acclimatizationplan_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomPackageRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(help_text='Desired destination', max_length=255)),
                ('alternative_destinations', models.TextField(blank=True, help_text='Alternative destinations (comma separated)')),
                ('preferred_start_date', models.DateField(help_text='Preferred start date')),
                ('preferred_end_date', models.DateField(help_text='Preferred end date')),
                ('flexible_dates', models.BooleanField(default=False, help_text='Are dates flexible?')),
                ('num_travelers', models.PositiveIntegerField(default=1, help_text='Number of travelers')),
                ('budget_min', models.DecimalField(decimal_places=2, help_text='Minimum budget per person', max_digits=10)),
                ('budget_max', models.DecimalField(decimal_places=2, help_text='Maximum budget per person', max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('activity_type', models.CharField(choices=[('trekking', 'Trekking'), ('peak_climbing', 'Peak Climbing'), ('tour', 'Cultural Tour'), ('wildlife', 'Wildlife Safari'), ('pilgrimage', 'Pilgrimage'), ('adventure', 'Adventure Sports'), ('mixed', 'Mixed Activities')], default='mixed', max_length=20)),
                ('accommodation_preference', models.CharField(blank=True, help_text='e.g., Hotel, Lodge, Camping', max_length=50)),
                ('guide_required', models.BooleanField(default=True)),
                ('special_requirements', models.TextField(blank=True, help_text='Dietary restrictions, accessibility needs, etc.')),
                ('additional_notes', models.TextField(blank=True, help_text='Any other information')),
                ('inspiration_image', models.ImageField(blank=True, help_text='Upload inspiration photos', null=True, upload_to='custom_requests/')),
                ('reference_document', models.FileField(blank=True, help_text='Upload itinerary ideas', null=True, upload_to='custom_requests/docs/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('REVIEWING', 'Under Review'), ('QUOTED', 'Quote Sent'), ('ACCEPTED', 'Quote Accepted'), ('REJECTED', 'Rejected'), ('CONVERTED', 'Converted to Booking')], default='PENDING', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes for admin')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Custom Package Request',
                'verbose_name_plural': 'Custom Package Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequestMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='request_messages/')),
                ('is_admin_message', models.BooleanField(default=False)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('custom_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='app.custompackagerequest')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequestQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_title', models.CharField(max_length=255)),
                ('description', models.TextField(help_text='Detailed package description')),
                ('itinerary', models.TextField(help_text='Day-by-day itinerary')),
                ('price_per_person', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('inclusions', models.TextField(help_text="What's included (one per line)")),
                ('exclusions', models.TextField(blank=True, help_text="What's not included (one per line)")),
                ('validity_days', models.PositiveIntegerField(default=7, help_text='Quote valid for how many days')),
                ('terms_and_conditions', models.TextField(blank=True)),
                ('advance_payment_percentage', models.DecimalField(decimal_places=2, default=30.0, help_text='Advance payment %', max_digits=5)),
                ('cancellation_policy', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('accepted', models.BooleanField(default=False)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('custom_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='app.custompackagerequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
