# Generated by Django 4.2.2 on 2026-03-25 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_guidemessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_at', models.DateTimeField(auto_now=True)),
                ('trek_type', models.CharField(default='easy', max_length=30)),
                ('season', models.CharField(default='autumn', max_length=20)),
                ('accommodation', models.CharField(default='teahouse', max_length=20)),
                ('ai_summary', models.TextField(blank=True, help_text='AI-generated trip summary/advisory')),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='packing_list', to='app.booking')),
            ],
            options={
                'ordering': ['booking__travel_date'],
            },
        ),
        migrations.CreateModel(
            name='PackingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('clothing', 'Clothing'), ('footwear', 'Footwear'), ('gear', 'Gear & Equipment'), ('health', 'Health & Safety'), ('documents', 'Documents & Money'), ('food_water', 'Food & Water'), ('electronics', 'Electronics'), ('camping', 'Camping Gear'), ('climbing', 'Climbing Gear'), ('seasonal', 'Seasonal Extras'), ('destination', 'Destination Specifics')], max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('priority', models.CharField(choices=[('essential', 'Essential'), ('recommended', 'Recommended'), ('optional', 'Optional')], default='essential', max_length=15)),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('is_checked', models.BooleanField(default=False)),
                ('per_person', models.BooleanField(default=False, help_text='Multiply quantity by num_people')),
                ('source', models.CharField(choices=[('base', 'Base'), ('ai', 'AI'), ('rule', 'Rule')], default='base', max_length=10)),
                ('packing_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app.packinglist')),
            ],
            options={
                'ordering': ['category', '-priority', 'name'],
            },
        ),
    ]
