# Generated by Django 4.2.2 on 2026-03-25 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_packing_list_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='trek_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='trekking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='app.trekking'),
        ),
    ]
