# Generated by Django 4.2.2 on 2026-03-26 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_booking_trekking_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestquote',
            name='confirmed_travel_date',
            field=models.DateField(blank=True, help_text='Confirmed travel date agreed with user', null=True),
        ),
        migrations.AlterField(
            model_name='requestquote',
            name='advance_payment_percentage',
            field=models.DecimalField(decimal_places=2, default=100, help_text='Advance payment %', max_digits=5),
        ),
    ]
