# Generated by Django 4.2.2 on 2026-03-26 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_quote_confirmed_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackingTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_type', models.CharField(choices=[('easy', 'Easy Trek / Tour'), ('moderate', 'Moderate Trek'), ('high_altitude', 'High Altitude Trek'), ('peak_climbing', 'Peak Climbing')], max_length=20)),
                ('season', models.CharField(choices=[('spring', 'Spring (Mar–May)'), ('monsoon', 'Monsoon (Jun–Aug)'), ('autumn', 'Autumn (Sep–Nov)'), ('winter', 'Winter (Dec–Feb)'), ('all', 'All Seasons')], max_length=10)),
                ('category', models.CharField(choices=[('clothing', 'Clothing'), ('footwear', 'Footwear'), ('gear', 'Gear & Equipment'), ('health', 'Health & Safety'), ('documents', 'Documents & Money'), ('food_water', 'Food & Water'), ('electronics', 'Electronics'), ('camping', 'Camping Gear'), ('climbing', 'Climbing Gear'), ('seasonal', 'Seasonal Extras'), ('destination', 'Destination Specifics')], max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('priority', models.CharField(choices=[('essential', 'Essential'), ('recommended', 'Recommended'), ('optional', 'Optional')], default='essential', max_length=15)),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('per_person', models.BooleanField(default=False)),
                ('notes', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['trip_type', 'season', 'category', '-priority', 'name'],
            },
        ),
    ]
