# Generated by Django 4.2.2 on 2026-03-26 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_packing_template'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packinglist',
            name='booking',
        ),
        migrations.DeleteModel(
            name='PackingItem',
        ),
        migrations.DeleteModel(
            name='PackingList',
        ),
    ]
