# Generated by Django 4.2.2 on 2026-03-29 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_weather_cache'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_currency', models.CharField(max_length=10, unique=True)),
                ('rates_json', models.TextField(help_text='JSON dict of currency→rate')),
                ('fetched_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Currency Rate Cache',
            },
        ),
    ]
