# Generated by Django 5.2.5 on 2026-01-04 14:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0006_booking_guide_booking_guide_rating_guidereview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emergency_type', models.CharField(max_length=50)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('critical', 'Critical')], max_length=10)),
                ('location', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True)),
                ('symptoms', models.TextField(blank=True)),
                ('altitude', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('raised', 'Raised'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved')], default='raised', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.booking')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
